//   Copyright 2016-2023 Jean-Francois Poilpret
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

/*
 * Prototype program to check implementation of ArduinoLCD display of a 
 * horizontal font generated by FastArduino FontEditor.
 * Wiring: 
 * - on ATmega328P based boards (including Arduino UNO):
 *   - D13 (SCK): connected to ArduinoLCD breakout SCK pin
 *   - D11 (MOSI): connected to ArduinoLCD breakout MOSI pin
 *   - D10: connected to ArduinoLCD breakout D/C pin
 *   - D9: connected to ArduinoLCD breakout LCD CS pin
 *   - D7: connected to ArduinoLCD breakout Reset pin
 *   - ArduinoLCD breakout LED pin connected to 5V via 1K resistor
 */

#include <fastarduino/devices/st7735.h>
#include <fastarduino/devices/display.h>
#include <fastarduino/utilities.h>
#include <fastarduino/time.h>
#include <fastarduino/flash.h>

#include "Font7x5.h"

#ifndef ARDUINO_UNO
#error "Current target is not supported!"
#endif

using namespace devices::display::st7735;

static constexpr const board::DigitalPin CS = board::DigitalPin::D9_PB1;
static constexpr const board::DigitalPin DC = board::DigitalPin::D10_PB2;
static constexpr const board::DigitalPin RES = board::DigitalPin::D7_PD7;

using DISPLAY = devices::display::Display<ARDUINO_IDE<CS, DC, RES, ColorModel::RGB_444, Orientation::LANDSCAPE>>;
using COLOR = DISPLAY::COLOR;
static constexpr uint8_t WIDTH = DISPLAY::WIDTH;
static constexpr uint8_t HEIGHT = DISPLAY::HEIGHT;
using devices::display::Mode;

static constexpr COLOR black = {0x00, 0x00, 0x00};
// static constexpr COLOR red = {0xFF, 0x00, 0x00};
// static constexpr COLOR green = {0x00, 0xFF, 0x00};
// static constexpr COLOR blue = {0x00, 0x00, 0xFF};
static constexpr COLOR white = {0xFF, 0xFF, 0xFF};

int main()
{
	board::init();
	sei();

	// Start SPI interface
	spi::init();
	
	// Start Arduino LCD device
	DISPLAY tft;
	tft.begin();
	tft.fill_screen(white);

	Font7x5 font{};
	tft.set_font(font);

	// Try font drawing
	tft.set_draw_mode({Mode::COPY, black});
	tft.set_fill_mode({Mode::COPY, white});
	const uint8_t FONT_WIDTH = font.width() + 1;
	const uint8_t FONT_HEIGHT = font.height() + 1;
	uint8_t xc = 0, yc = 0;
	for (char c = font.first_char(); c <= font.last_char(); ++c)
	{
		tft.draw_char({xc, yc}, c);
		xc += FONT_WIDTH;
		if (xc > WIDTH - FONT_WIDTH)
		{
			xc = 0;
			yc += FONT_HEIGHT;
		}
	}
	time::delay_ms(2000);

	// Try display inversion
	tft.invert_on();
	time::delay_ms(2000);
	tft.invert_off();
}
