#!/bin/bash
#
# This script helps preparing documentation for a release:
# 1. Build all tutorial samples (for Arduino API and FastArduino)
# 2. Gather make output and prepare code size sheets of samples
# 3. Generate size tables for inclusion into tutorial doc
# 4. Regenerate docs

CURDIR=`pwd`
SCRIPT=$(readlink -f "$0")
MAKEDIR=$(dirname "$SCRIPT")
BASEDIR=$MAKEDIR/..

echo "Build all samples for Arduino API"
cd $BASEDIR/tuto-samples/arduino
./build-samples | ./stats.py >sizes.txt

echo "Build all samples for FastArduino"
cd $BASEDIR/tuto-samples/fastarduino
./build-samples 2>errors| ./stats.py >sizes.txt

# check if error found, then abort
cd $CURDIR
grep "Error" $BASEDIR/tuto-samples/fastarduino/errors
if [ $? -ne 1 ]; then
	echo "Error occurred, aborting."
	exit 1
fi

# Generate size tables 
echo "Generate size data sheets"
$MAKEDIR/gen-sample-size-tables.py $BASEDIR/tuto-samples/arduino/sizes.txt $BASEDIR/tuto-samples/fastarduino/sizes.txt $MAKEDIR/samples-list.txt >$BASEDIR/tuto-samples/tables.txt

echo "Generate docs"
cd $BASEDIR
make doco
cd $CURDIR
