#!/bin/bash
CURDIR=`pwd`
SCRIPT=$(readlink -f "$0")
MAKEDIR=$(dirname "$SCRIPT")
BASEDIR=$MAKEDIR/..
cd $BASEDIR
make clean-examples CONF=UNO
~/sonar-wrapper --out-dir ../sonar make examples CONF=UNO
~/sonar-scanner -Dsonar.projectKey=FastArduino-UNO -Dsonar.sources=cores,examples -Dsonar.cfamily.build-wrapper-output=../sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jfpoilpret-github -Dsonar.login=$SONAR_TOKEN -Dsonar.cfamily.threads=4
cd $CURDIR
